
package vistas;

import controladores.CtrlEliminarHistorial;
import controladores.CtrlEliminarMedico;
import controladores.CtrlEliminarPaciente;
import controladores.CtrlModificarHistorial;
import controladores.CtrlModificarMedico;
import controladores.CtrlModificarPaciente;
import controladores.CtrlMostrarHistorial;
import controladores.CtrlMostrarMedicos;
import controladores.CtrlMostrarPacientes;
import controladores.CtrlRegistrarHistorial;
import controladores.CtrlRegistrarMedico;
import controladores.CtrlRegistrarPaciente;


/**
 *
 * @author lairinyssilva
 */
public class ViewMenuSecundario extends javax.swing.JFrame {

    /**
     * Creates new form ViewMenuPrincipal
     */
    public ViewMenuSecundario() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnModificar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        btnMostrar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Historias Clínicas");
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        btnModificar.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/006-pencil.png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.setAlignmentY(0.0F);
        btnModificar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnModificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnModificar.setPreferredSize(new java.awt.Dimension(220, 80));
        btnModificar.setSize(new java.awt.Dimension(220, 0));
        btnModificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnRegistrar.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/005-plus.png"))); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.setAlignmentY(0.0F);
        btnRegistrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegistrar.setContentAreaFilled(false);
        btnRegistrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegistrar.setPreferredSize(new java.awt.Dimension(220, 80));
        btnRegistrar.setSize(new java.awt.Dimension(220, 0));
        btnRegistrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnMostrar.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnMostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/010-search.png"))); // NOI18N
        btnMostrar.setText("Mostrar");
        btnMostrar.setToolTipText("");
        btnMostrar.setAlignmentY(0.0F);
        btnMostrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMostrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMostrar.setPreferredSize(new java.awt.Dimension(220, 80));
        btnMostrar.setSize(new java.awt.Dimension(220, 0));
        btnMostrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/007-minus.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setAlignmentY(0.0F);
        btnEliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminar.setPreferredSize(new java.awt.Dimension(220, 80));
        btnEliminar.setSize(new java.awt.Dimension(220, 0));
        btnEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));

        btnSalir.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/013-exit-1.png"))); // NOI18N
        btnSalir.setBorderPainted(false);
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Gestionar");
        lblTitulo.setName(""); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSalir)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTitulo)
                        .addGap(26, 26, 26))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnMostrar, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                    .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(39, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                    .addComponent(btnMostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                    .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        setBounds(0, 0, 468, 450);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
         
        switch(this.btnRegistrar.getText()){
            case "Registrar Pacientes":   
                CtrlRegistrarPaciente formPaciente=new CtrlRegistrarPaciente();
                break;
                
            case "Registrar Médicos":
                CtrlRegistrarMedico formMedico=new CtrlRegistrarMedico();
                break;
                
            case "Registrar Historial":
                CtrlRegistrarHistorial formHistorial=new CtrlRegistrarHistorial();
                break;
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        switch(this.btnModificar.getText()){
            case "Modificar Pacientes":   
                CtrlModificarPaciente formPaciente=new CtrlModificarPaciente();
                break;
                
            case "Modificar Médicos":
                CtrlModificarMedico formMedico=new CtrlModificarMedico();
                break;
                
            case "Modificar Historial":
                CtrlModificarHistorial formHistorial=new CtrlModificarHistorial();
                break;
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        switch(this.btnEliminar.getText()){
            case "Eliminar Pacientes":   
                CtrlEliminarPaciente formPacientes=new CtrlEliminarPaciente();
                break;
                
            case "Eliminar Médicos":
                CtrlEliminarMedico formMedicos=new CtrlEliminarMedico();
                break;
                
            case "Eliminar Historial":
                CtrlEliminarHistorial formHistorial=new CtrlEliminarHistorial();
                break;
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        
        switch(this.btnMostrar.getText()){
            case "Mostrar Pacientes":   
                CtrlMostrarPacientes formPacientes=new CtrlMostrarPacientes();
                break;
                
            case "Mostrar Médicos":
                CtrlMostrarMedicos formMedicos=new CtrlMostrarMedicos();
                break;
                
            case "Mostrar Historial":
                CtrlMostrarHistorial formHistorial=new CtrlMostrarHistorial();
                break;
        }
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
      // historiasmedicas.HistoriasMedicas.Principal.setEnabled(true);
    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
           
        historiasmedicas.HistoriasMedicas.Principal.regresar();
   
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ViewMenuSecundario().setVisible(true);
        });
    }
   
    public void configurar(ViewMenuSecundario secundario,String tipo){
        
        secundario.lblTitulo.setText("Gestionar "+tipo);
        secundario.btnModificar.setText("Modificar "+tipo);
        secundario.btnMostrar.setText("Mostrar "+tipo);
        secundario.btnRegistrar.setText("Registrar "+tipo);
        secundario.btnEliminar.setText("Eliminar "+tipo);
        secundario.setLocationRelativeTo(null);
    }
     
    
    private void abrirForm(ViewRegistrarPersona formulario) {
        //formulario.setVisible(true);
        //formulario.setLocationRelativeTo(null);
        desactivarme();
        
    } 
    
    
    private void desactivarme(){
        this.btnEliminar.setEnabled(false);
        this.btnModificar.setEnabled(false);
        this.btnMostrar.setEnabled(false);
        this.btnRegistrar.setEnabled(false);
    }
   
    public void regresar(){
        this.setBtnEliminarEnabled(true);
        this.setBtnModificarEnabled(true);
        this.setBtnMostrarEnabled(true);
        this.setBtnRegistrarEnabled(true);
    }

    
    public void setBtnEliminarEnabled(boolean valor) {
        this.btnEliminar.setEnabled(valor);
    }

    public void setBtnModificarEnabled(boolean valor) {
        this.btnModificar.setEnabled(valor);
    }

    public void setBtnMostrarEnabled(boolean valor) {
        this.btnMostrar.setEnabled(valor);
    }
    public void setBtnRegistrarEnabled(boolean valor) {
        this.btnMostrar.setEnabled(valor);
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables



}
